// skyjs cluster API (Task 6). Protocol-compatible with the original skynet
// cluster: frames are built by cservice/skyclusterd.so, lua-seri payloads are
// produced/consumed here with skynet.pack/unpack.
//
// Usage:
//   cluster.init()                       locate ".clusterd" (must be launched)
//   cluster.set_nodes({ n1: "ip:port" })  declare remote node addresses
//   cluster.open(port)                   accept remote connections
//   cluster.register("name")             publish a local name
//   await cluster.call(node, "@name", ...args)  -> unpacked response values
//   cluster.send(node, "@name", ...args)        one-way
//   await cluster.query(node, "name")    resolve a remote registered name
(function () {
    "use strict";

    const PTYPE_TEXT = 0;
    const CLUSTER_TIMEOUT = 3000;  // 30 seconds in centiseconds
    let clusterd = 0;
    const pending = new Map();   // js_session -> { resolve, reject }

    __snjs_set_cluster_handlers(
        (session, msg) => {
            const p = pending.get(session);
            if (p) {
                pending.delete(session);
                p.resolve(msg);
            }
        },
        (session) => {
            const p = pending.get(session);
            if (p) {
                pending.delete(session);
                p.reject(new Error("cluster.call failed (error response)"));
            }
        }
    );

    function init() {
        clusterd = skynetcore.int_command("QUERY", ".clusterd");
        if (!clusterd) throw new Error("cluster: .clusterd not found, launch skyclusterd first");
    }

    // send a command line (+ optional binary payload) to skyclusterd.
    // session must be pre-generated by the caller; throws on send failure.
    function raw_cmd(session, line, payload_bytes) {
        const head = new Uint8Array(line.length + 1);
        for (let i = 0; i < line.length; i++) head[i] = line.charCodeAt(i) & 0xff;
        head[line.length] = 10;	// '\n'
        let msg = head;
        if (payload_bytes) {
            msg = new Uint8Array(head.length + payload_bytes.length);
            msg.set(head, 0);
            msg.set(payload_bytes, head.length);
        }
        const r = skynetcore.send(clusterd, PTYPE_TEXT, msg.buffer, session);
        if (r < 0) {
            throw new Error("cluster: send to clusterd failed");
        }
    }

    // fire-and-forget variant: generates its own session, ignores result
    function raw_cmd_fire(line) {
        const s = skynetcore.gen_id();
        const head = new Uint8Array(line.length + 1);
        for (let i = 0; i < line.length; i++) head[i] = line.charCodeAt(i) & 0xff;
        head[line.length] = 10;	// '\n'
        skynetcore.send(clusterd, PTYPE_TEXT, head.buffer, s);
    }

    function addr_str(addr) {
        // numeric handles cross as hex strings; names get the '@' prefix
        if (typeof addr === "number") return addr.toString(16);
        return addr.charCodeAt(0) === 64 ? addr : "@" + addr;
    }

    globalThis.cluster = {
        init,
        set_nodes(obj) {
            for (const k in obj) {
                const sep = obj[k].lastIndexOf(":");
                raw_cmd_fire("node " + k + " " + obj[k].slice(0, sep) + " " + obj[k].slice(sep + 1));
            }
        },
        open(port) {
            raw_cmd_fire("listen " + port);
        },
        register(name) {
            raw_cmd_fire("register " + name);
        },
        call(node, addr, ...vals) {
            const payload = new Uint8Array(skynet.pack(...vals));
            return new Promise((resolve, reject) => {
                const session = skynetcore.gen_id();
                pending.set(session, {
                    resolve: (ab) => resolve(skynet.unpack(ab)),
                    reject,
                });
                try {
                    raw_cmd(session, "req " + node + " " + addr_str(addr), payload);
                } catch (e) {
                    pending.delete(session);
                    reject(e);
                    return;
                }
                skynet.timeout(CLUSTER_TIMEOUT, () => {
                    if (pending.has(session)) {
                        pending.delete(session);
                        reject(new Error("cluster.call timeout: node=" + node + " addr=" + addr));
                    }
                });
            });
        },
        send(node, addr, ...vals) {
            const payload = new Uint8Array(skynet.pack(...vals));
            const s = skynetcore.gen_id();
            try {
                raw_cmd(s, "push " + node + " " + addr_str(addr), payload);
            } catch (_) {
                // fire-and-forget: log but do not propagate
                skynetcore.error("cluster.send failed: node=" + node + " addr=" + addr);
            }
        },
        query(node, name) {
            const payload = new Uint8Array(skynet.pack(name));
            return new Promise((resolve, reject) => {
                const session = skynetcore.gen_id();
                pending.set(session, {
                    resolve: (ab) => resolve(skynet.unpack(ab)[0]),
                    reject,
                });
                try {
                    raw_cmd(session, "req " + node + " 0", payload);
                } catch (e) {
                    pending.delete(session);
                    reject(e);
                    return;
                }
                skynet.timeout(CLUSTER_TIMEOUT, () => {
                    if (pending.has(session)) {
                        pending.delete(session);
                        reject(new Error("cluster.query timeout: node=" + node + " name=" + name));
                    }
                });
            });
        },
    };
})();
