// Task 5 acceptance: lua-seri compatibility.
// 1. unpack the Lua-generated reference file (seri_tool gen) and assert values
// 2. repack the same sequence: byte-exact vs the reference (scalars+array table)
// 3. write a JS-packed file for seri_tool dump inspection
// 4. PTYPE_LUA roundtrip between two JS services (ArrayBuffer payloads)

const seri_b_h = skynetcore.int_command("LAUNCH", "snjs test/service/js_seri_b.js");
skynet.register("main");
skynetcore.int_command("LAUNCH", "driver .main 300 start 0");

function check(cond, name) {
    if (!cond) skynetcore.error("SERI FAIL: " + name);
    return !!cond;
}

skynet.start(() => {
    skynet.dispatch("text", async (msg) => {
        if (msg !== "start") return "OK";

        const ref = new Uint8Array(skynetcore.read_file("build/seri_ref.bin"));
        const vals = skynet.unpack(ref.buffer);
        let ok = true;
        ok = check(vals[0] === null, "nil") && ok;
        ok = check(vals[1] === true, "bool true") && ok;
        ok = check(vals[2] === false, "bool false") && ok;
        ok = check(vals[3] === 0, "int 0") && ok;
        ok = check(vals[4] === 1, "int 1") && ok;
        ok = check(vals[5] === 200, "int 200") && ok;
        ok = check(vals[6] === 70000, "int 70000") && ok;
        ok = check(vals[7] === -1234567, "int -1234567") && ok;
        ok = check(vals[8] === 5000000000n, "qword bigint") && ok;
        ok = check(vals[9] === 1.5, "real 1.5") && ok;
        ok = check(vals[10] === 0.25, "real 0.25") && ok;
        ok = check(vals[11] === "hello", "string") && ok;
        ok = check(vals[12] === "x".repeat(100), "long string") && ok;
        const t1 = vals[13];
        skynetcore.error("SERI t1 = " + JSON.stringify(t1 && [...t1.entries()]));
        ok = check(t1 instanceof Map && t1.get(1) === 10 && t1.get(2) === 20 && t1.get(3) === 30, "array table") && ok;

        // byte-exact roundtrip: same value sequence repacked must equal the
        // Lua-generated bytes (scalars + array table are order-stable)
        const repacked = new Uint8Array(skynet.pack(
            vals[0], vals[1], vals[2], vals[3], vals[4], vals[5], vals[6],
            vals[7], vals[8], vals[9], vals[10], vals[11], vals[12], [10, 20, 30]));
        let byte_eq = repacked.length === ref.length;
        if (byte_eq) {
            for (let i = 0; i < ref.length; i++) {
                if (repacked[i] !== ref[i]) { byte_eq = false; break; }
            }
        }
        ok = check(byte_eq, "byte-exact roundtrip (len " + repacked.length + " vs " + ref.length + ")") && ok;

        // JS -> file, later inspected with: test/seri_tool dump /tmp/seri_js.bin
        skynetcore.write_file("/tmp/seri_js.bin", skynet.pack(
            "two", 1, new Map([["k", 5n], ["pi", 3.14]]), [1, new Map()]));
        skynetcore.error("SERI wrote /tmp/seri_js.bin");

        // PTYPE_LUA roundtrip between two JS services
        const sent = skynet.pack("msg", 42, [1, 2]);
        skynetcore.error("SERI sent bytes: " + JSON.stringify(Array.from(new Uint8Array(sent))));
        const back = await skynet.call(seri_b_h, "lua", sent);
        skynetcore.error("SERI back bytes: " + JSON.stringify(Array.from(new Uint8Array(back))));
        const rb = skynet.unpack(back);
        skynetcore.error("SERI rb = " + JSON.stringify(rb.map(v => v instanceof Map ? [...v.entries()] : (typeof v === "bigint" ? v.toString() + "n" : v))));
        ok = check(rb[0] === "seri_b_ok" && rb[1] === 43 && rb[2] instanceof Map &&
            rb[2].get(1) === 1 && rb[2].get(2) === 2, "lua protocol roundtrip") && ok;

        skynetcore.error("SERI RESULT: " + (ok ? "ALL_OK" : "FAILED"));
        return ok ? "SERI_ALL_OK" : "SERI_FAILED";
    });
});
